### ISSUE TITLE
SSL ImageNet DM not working in MoCo example

### ISSUE THREAD

**Issue by vobecant** [PyTorchLightning/lightning-bolts#345]
## 🐛 Bug

SSL ImageNet datamodule is not working in MoCo example.

### To Reproduce

1. Go to 'pl_bolts/models/self_supervised/moco'
2. Run
`python moco2_module.py --gpus 1 --dataset imagenet2012 --data_dir /nfs/datasets/imagenet/imagenet12/ --meta_dir /nfs/datasets/imagenet/imagenet12/ --batch_size 32`
3. See error
`TypeError: val_dataloader() missing 1 required positional argument: 'batch_size'`

Full stack trace:
```
Traceback (most recent call last):
  File "moco2_module.py", line 393, in <module>
    cli_main()
  File "moco2_module.py", line 389, in cli_main
    trainer.fit(model, datamodule=datamodule)
  File "pytorch_lightning/trainer/trainer.py", line 440, in fit
    results = self.accelerator_backend.train()
  File "/pytorch_lightning/accelerators/gpu_accelerator.py", line 54, in train
    results = self.train_or_test()
  File "/pytorch_lightning/accelerators/accelerator.py", line 66, in train_or_test
    results = self.trainer.train()
  File "/pytorch_lightning/trainer/trainer.py", line 462, in train
    self.run_sanity_check(self.get_model())
  File "/pytorch_lightning/trainer/trainer.py", line 638, in run_sanity_check
    self.reset_val_dataloader(ref_model)
  File "/pytorch_lightning/trainer/data_loading.py", line 316, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File "/pytorch_lightning/trainer/data_loading.py", line 236, in _reset_eval_dataloader
    dataloaders = self.request_dataloader(getattr(model, loader_name))
  File "/pytorch_lightning/trainer/data_loading.py", line 339, in request_dataloader
    dataloader = dataloader_fx()
TypeError: val_dataloader() missing 1 required positional argument: 'batch_size'
```

#### Code sample
1. Go to 'pl_bolts/models/self_supervised/moco'
2. Run
`python moco2_module.py --gpus 1 --dataset imagenet2012 --data_dir /nfs/datasets/imagenet/imagenet12/ --meta_dir /nfs/datasets/imagenet/imagenet12/ --batch_size 32`

### Expected behavior
Working ImageNet datamodule for SSL.

### Environment

 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Borda** [comment]
@ananyahjha93 any update here?

**Comment by ananyahjha93** [comment]
We are deprecating the self-supervised learning paper implementations in bolts and instead provided a [VISSL](https://vissl.ai/) integration in PyTorch Lightning Flash which can be used to train models using self-supervised learning algorithms. You can refer to the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/image_embedder.html).
