### ISSUE TITLE
Training BYOL on multiple GPUs using "dp" and "ddp" accelerators error

### ISSUE THREAD

**Issue by azamshoaib** [PyTorchLightning/lightning-bolts#385]
## Bug
I trained the BYOL implementation provided in the bolts on multiple GPUs using the accelerator "dp" and "ddp" respectively, but got the following errors
Using  "dp"
```
File "pytorch-lightning-bolts/pl_bolts/models/self_supervised/byol/byol_module.py", line 227, in <module>
    cli_main()
  File "pytorch-lightning-bolts/pl_bolts/models/self_supervised/byol/byol_module.py", line 223, in cli_main
    trainer.fit(model, dm)
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 444, in fit
    results = self.accelerator_backend.train()
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/accelerators/dp_accelerator.py", line 106, in train
    results = self.train_or_test()
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 493, in train
    self.train_loop.run_training_epoch()
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 589, in run_training_epoch
    self.trainer.run_evaluation(test_mode=False)
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 609, in run_evaluation
    eval_loop_results = self.evaluation_loop.log_epoch_metrics(deprecated_eval_results, epoch_logs, test_mode)
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 214, in log_epoch_metrics
    test_mode
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/logger_connector.py", line 113, in on_evaluation_epoch_end
    self._log_on_evaluation_epoch_end_metrics(epoch_logs)
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/logger_connector.py", line 181, in _log_on_evaluation_epoch_end_metrics
    reduced_epoch_metrics = dl_metrics[0].__class__.reduce_on_epoch_end(dl_metrics)
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/core/step_result.py", line 464, in reduce_on_epoch_end
    recursive_stack(result)
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/core/step_result.py", line 603, in recursive_stack
    result[k] = collate_tensors(v)
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/core/step_result.py", line 625, in collate_tensors
    return torch.stack(items)
RuntimeError: All input tensors must be on the same device. Received cuda:0 and cuda:1
Exception ignored in: <function tqdm.__del__ at 0x7f5942667680>
Traceback (most recent call last):
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/tqdm/std.py", line 1087, in __del__
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/tqdm/std.py", line 1294, in close
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/tqdm/std.py", line 1472, in display
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/tqdm/std.py", line 1090, in __repr__
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/tqdm/std.py", line 1434, in format_dict
TypeError: cannot unpack non-iterable NoneType object
```

Using "ddp"
```
Traceback (most recent call last):
  File "/home/shoaib/work/research/paper-1/self-supervised/pytorch-lightning-bolts/pl_bolts/models/self_supervised/byol/byol_module.py", line 227, in <module>
  File "pytorch-lightning-bolts/pl_bolts/models/self_supervised/byol/byol_module.py", line 227, in <module>
    cli_main()
    cli_main()
  File "pytorch-lightning-bolts/pl_bolts/models/self_supervised/byol/byol_module.py", line 223, in cli_main
  File "/home/shoaib/work/research/paper-1/self-supervised/pytorch-lightning-bolts/pl_bolts/models/self_supervised/byol/byol_module.py", line 223, in cli_main
    trainer.fit(model, dm)
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 444, in fit
    trainer.fit(model, dm)
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 444, in fit
    results = self.accelerator_backend.train()
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 148, in train
    results = self.accelerator_backend.train()
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 148, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 241, in ddp_train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 241, in ddp_train
    self.trainer.is_slurm_managing_tasks
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 216, in init_ddp_connection
    self.trainer.is_slurm_managing_tasks
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 216, in init_ddp_connection
    torch_backend, rank=global_rank, world_size=world_size
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    torch_backend, rank=global_rank, world_size=world_size
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    barrier()
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1947, in barrier
    barrier()
  File "/home/shoaib/miniconda3/envs/pylight/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1947, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
```

The environment details are as follows:
Pytorch-1.7.0
Pytorch_lightning-1.0.6
OS-Ubuntu-18

Kindly help me in this regard. Thank you.

**Comment by Borda** [comment]
@ananyahjha93 any update here?

**Comment by ananyahjha93** [comment]
We are deprecating the self-supervised learning paper implementations in bolts and instead provided a [VISSL](https://vissl.ai/) integration in PyTorch Lightning Flash which can be used to train models using self-supervised learning algorithms. You can refer to the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/image_embedder.html).
