### ISSUE TITLE
Training STL10 with Moco

### ISSUE THREAD

**Issue by dvd42** [PyTorchLightning/lightning-bolts#456]
## 🐛 Bug

I get the following error when trying to train MocoV2 with STL10

```
  File "/home/diego/.pyenv/versions/adversarial/lib/python3.7/site-packages/pl_bolts/models/self_supervised/moco/moco2_module.py", line 287, in validation_step
 (img_1, img_2), labels = batch
ValueError: too many values to unpack (expected 2)

```
### To Reproduce

```python
  dm = STL10DataModule(data_dir="data/datasets")
  dm.train_transforms = SimCLRTrainDataTransform(32)
  dm.val_transforms = SimCLREvalDataTransform(32)

  wandb_logger = pl.loggers.WandbLogger(project="SSL-EP", save_dir="output")
  model = MocoV2(datamodule=dm, data_dir="output")
  trainer = pl.Trainer(gpus=1, logger=wandb_logger)
  trainer.fit(model, dm)
```

#### Full stack trace
```
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "main.py", line 27, in <module>
    trainer.fit(model, dm)
  File "/home/diego/.pyenv/versions/adversarial/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 470, in fit
    results = self.accelerator_backend.train()
  File "/home/diego/.pyenv/versions/adversarial/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 66, in train
    results = self.train_or_test()
  File "/home/diego/.pyenv/versions/adversarial/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 65, in train_or_test
    results = self.trainer.train()
  File "/home/diego/.pyenv/versions/adversarial/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 492, in train
    self.run_sanity_check(self.get_model())
  File "/home/diego/.pyenv/versions/adversarial/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 690, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val
wandb: Waiting for W&B process to finish, PID 29005
_batches)
  File "/home/diego/.pyenv/versions/adversarial/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 606, in run_evaluation
    output = self.evaluation_loop.evaluation_step(test_mode, batch, batch_idx, dataloader_idx)
  File "/home/diego/.pyenv/versions/adversarial/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 178, in evaluation_step
    output = self.trainer.accelerator_backend.validation_step(args)
  File "/home/diego/.pyenv/versions/adversarial/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 84, in validation_step
    return self._step(self.trainer.model.validation_step, args)
  File "/home/diego/.pyenv/versions/adversarial/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 76, in _step
    output = model_step(*args)
  File "/home/diego/.pyenv/versions/adversarial/lib/python3.7/site-packages/pl_bolts/models/self_supervised/moco/moco2_module.py", line 287, in validation_step
    (img_1, img_2), labels = batch
ValueError: too many values to unpack (expected 2)


```

### Environment

 - PyTorch Version: 1.6 (installed with pip)
 - OS (e.g., Linux): Linux Mint
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2/7.6.4
 - GPU models and configuration: 1080ti

### Additional context
The same exact script works with the `CIFAR10DataModule`

**Comment by Borda** [comment]
@ananyahjha93 any update here? :]

**Comment by kcetskcaz** [comment]
If you look at the SimCLRTrainDataTransform implementation, you'll find that 3 augmentations of the input sample are returned from the `__call__` method. However, if you look at any of the MoCoV2 transforms, you'll see that the `__call__` methods only return **2** augmentations of the input sample.

### SimCLRTrainDataTransform

```
def __call__(self, sample):
        transform = self.train_transform

        xi = transform(sample)
        xj = transform(sample)

        return xi, xj, self.online_transform(sample)
```

### Moco2Train<dataset>Transform

```
def __call__(self, inp):
        q = self.train_transform(inp)
        k = self.train_transform(inp)
        return q, k
```

Following above, SimCLR expects the datamodule to return **3** augmentations of the input- hence the tuple is unpacking 3 objects from the `batch` variable in the SimCLR training/validation steps. However, MoCoV2 expects the datamodule to only return **2** augmentations of the input- hence the tuple is only unpacking 2 objects from the `batch` variable.

### Found in SimCLR Train/Val steps
```
(img1, img2, _), y = batch
```

### Found in MoCoV2 Train/Val steps
```
(img_1, img_2), label = batch
```

# Conclusion and Solution

**Solution**: When using MoCoV2, use one of the provided Moco2Train<dataset>Transform classes or a custom transform that only returns 2 augmentations of the input sample.

The issue OP posted isn't a bug so much as a reasonable misunderstanding of what the different transforms are actually doing. It's very reasonable to assume this is a bug given how similar SimCLR and MoCoV2 are on paper, and it's not until digging around under the hood that we see otherwise. I hope this helps @Borda and @dvd42 !
