### ISSUE TITLE
SwAV: validation sanity check fails

### ISSUE THREAD

**Issue by RGring** [PyTorchLightning/lightning-bolts#459]
Hi,
Thanks for this great repo :)
## 🐛 Bug
When I run the example code of SwAv (https://pytorch-lightning-bolts.readthedocs.io/en/latest/self_supervised_models.html#swav), it doesn't pass the validation sanity check.

### To Reproduce
Run the following (from the example, while I changed trainer.fit(model) to trainer.fit(model, dm)):
```py
import pytorch_lightning as pl
from pl_bolts.models.self_supervised import SwAV
from pl_bolts.datamodules import STL10DataModule
from pl_bolts.models.self_supervised.swav.transforms import (
    SwAVTrainDataTransform, SwAVEvalDataTransform
)
from pl_bolts.transforms.dataset_normalizations import stl10_normalization

# data
batch_size = 128
dm = STL10DataModule(data_dir='.', batch_size=batch_size)
dm.train_dataloader = dm.train_dataloader_mixed
dm.val_dataloader = dm.val_dataloader_mixed

dm.train_transforms = SwAVTrainDataTransform(
    normalize=stl10_normalization()
)

dm.val_transforms = SwAVEvalDataTransform(
    normalize=stl10_normalization()
)

# model
model = SwAV(
    gpus=1,
    num_samples=dm.num_unlabeled_samples,
    dataset='stl10',
    batch_size=batch_size
)

# fit
trainer = pl.Trainer(precision=16)
trainer.fit(model, dm)
```

I get:
```
UserWarning: You want to use `gym` which is not installed yet, install it with `pip install gym`.
  stdout_func(f'You want to use `{pkg_name}` which is not installed yet,'
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Using native 16bit precision.
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified

  | Name    | Type    | Params
------------------------------------
0 | model   | ResNet  | 28.4 M
1 | softmax | Softmax | 0     
------------------------------------
28.4 M    Trainable params
0         Non-trainable params
28.4 M    Total params
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "swav/main_swav4.py", line 34, in <module>
    trainer.fit(model, dm)
  File "/zhome/d6/0/152995/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 470, in fit
    results = self.accelerator_backend.train()
  File "/zhome/d6/0/152995/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 68, in train
    results = self.train_or_test()
  File "/zhome/d6/0/152995/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 69, in train_or_test
    results = self.trainer.train()
  File "/zhome/d6/0/152995/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 492, in train
    self.run_sanity_check(self.get_model())
  File "/zhome/d6/0/152995/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 690, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/zhome/d6/0/152995/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 606, in run_evaluation
    output = self.evaluation_loop.evaluation_step(test_mode, batch, batch_idx, dataloader_idx)
  File "/zhome/d6/0/152995/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 178, in evaluation_step
    output = self.trainer.accelerator_backend.validation_step(args)
  File "/zhome/d6/0/152995/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 86, in validation_step
    return self._step(self.trainer.model.validation_step, args)
  File "/zhome/d6/0/152995/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 76, in _step
    output = model_step(*args)
  File "/zhome/d6/0/152995/.local/lib/python3.8/site-packages/pl_bolts/models/self_supervised/swav/swav_module.py", line 276, in validation_step
    loss = self.shared_step(batch)
  File "/zhome/d6/0/152995/.local/lib/python3.8/site-packages/pl_bolts/models/self_supervised/swav/swav_module.py", line 263, in shared_step
    subloss -= torch.mean(torch.sum(q * torch.log(p), dim=1))
RuntimeError: The size of tensor a (128) must match the size of tensor b (0) at non-singleton dimension 0
```
Thanks in advance!

**Comment by VirtualSpaceman** [comment]
Hello @RGring !

I don't know if you already solved the error, but  I've found a workaround for this issue. I was able to run the method by manually downloading the [swav_module.py](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/pl_bolts/models/self_supervised/swav/swav_module.py) file from the main repo, then running as a normal Python script. I was facing this [PyTorch Lightning Issue](https://github.com/PyTorchLightning/pytorch-lightning/issues/5162) when setting `precision=16` as a parameter, but changed it to `precision=32` and It started working.

**Comment by ananyahjha93** [comment]
@RGring can you try installing bolts from master. That should have the fix for now.

**Comment by akihironitta** [comment]
@RGring Could you follow @ananyahjha93's comment above? If it still doesn't work, please feel free to reopen this issue.

**Comment by HareshKarnan** [comment]
Issue still occurs with master branch.

**Comment by ananyahjha93** [comment]
@RGring @HareshKarnan nmb_crops argument needs to be passed to SwAV and DataTransforms. The defaults are set to different values for the 2 classes, hence the issue. I'll add in a fix.

**Comment by RGring** [comment]
@ananyahjha93 Yes setting the nmb_crops to the same as in the defaults helped.

**Comment by Borda** [comment]
@ananyahjha93 any update here?

**Comment by ananyahjha93** [comment]
We are deprecating the self-supervised learning paper implementations in bolts and instead provided a [VISSL](https://vissl.ai/) integration in PyTorch Lightning Flash which can be used to train models using self-supervised learning algorithms. You can refer to the documentation [here](https://lightning-flash.readthedocs.io/en/latest/reference/image_embedder.html).
